// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnnkbH3qJehVfVkriCBvFvz-ej0Ejv3Mk',
    appId: '1:1076208018232:web:547fd6c65bc011252597cd',
    messagingSenderId: '1076208018232',
    projectId: 'autbody',
    authDomain: 'autbody.firebaseapp.com',
    storageBucket: 'autbody.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtwD4-6yewP0I7ZQ6sddi5zVIkTqBYlm0',
    appId: '1:1076208018232:android:ee1c42722ace9c1b2597cd',
    messagingSenderId: '1076208018232',
    projectId: 'autbody',
    storageBucket: 'autbody.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGfmkai8tharYswl6d_Te2axUcOmOPygA',
    appId: '1:1076208018232:ios:be5603c9f7e7a3c62597cd',
    messagingSenderId: '1076208018232',
    projectId: 'autbody',
    storageBucket: 'autbody.appspot.com',
    iosClientId: '1076208018232-mpf31op0lvchpb58ft06tr0u276d33fu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitbodyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGfmkai8tharYswl6d_Te2axUcOmOPygA',
    appId: '1:1076208018232:ios:be5603c9f7e7a3c62597cd',
    messagingSenderId: '1076208018232',
    projectId: 'autbody',
    storageBucket: 'autbody.appspot.com',
    iosClientId: '1076208018232-mpf31op0lvchpb58ft06tr0u276d33fu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitbodyFlutter',
  );
}
